<a href="https://colab.research.google.com/github/RXHem/Bottyforfun/blob/main/Copy_of_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
train_data[0]
train_labels[0]

import numpy as np


def vectorize_sequences(sequences, dimension=10000):
  # Creates an all-zero matrix
  results = np.zeros((len(sequences), dimension))
  # Set approperiate indices of the tensor result to 1s
  for i, sequence in enumerate(sequences):
    results[i, sequence] = 1.
  return results

# Turn Python lists into NumPy tensors
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

# print out parts of x_train to see what is in it...
print(x_train[:9])


y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

# print out parts of y_train to see what is in it...
print(y_train[:9])

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
[1. 0. 0. 1. 0. 0. 1. 0. 1.]


In [ ]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
# Setting aside a validation set
x_val = x_train[:10000]
partial_x_train = x_train[10000:]

y_val = y_train[:10000]
partial_y_train = y_train[10000:]

# Training the model
model.fit(partial_x_train,
          partial_y_train,
          epochs=20,
          batch_size=512,
          validation_data=(x_val, y_val))


Epoch 1/20
30/30 [==============================] - 6s 89ms/step - loss: 0.4990 - accuracy: 0.8047 - val_loss: 0.3810 - val_accuracy: 0.8713
Epoch 2/20
30/30 [==============================] - 1s 47ms/step - loss: 0.2985 - accuracy: 0.9059 - val_loss: 0.3002 - val_accuracy: 0.8874
Epoch 3/20
30/30 [==============================] - 1s 36ms/step - loss: 0.2207 - accuracy: 0.9267 - val_loss: 0.2800 - val_accuracy: 0.8879
Epoch 4/20
30/30 [==============================] - 1s 36ms/step - loss: 0.1746 - accuracy: 0.9448 - val_loss: 0.2732 - val_accuracy: 0.8894
Epoch 5/20
30/30 [==============================] - 1s 36ms/step - loss: 0.1401 - accuracy: 0.9553 - val_loss: 0.2926 - val_accuracy: 0.8856
Epoch 6/20
30/30 [==============================] - 1s 37ms/step - loss: 0.1178 - accuracy: 0.9635 - val_loss: 0.3051 - val_accuracy: 0.8828
Epoch 7/20
30/30 [==============================] - 1s 36ms/step - loss: 0.0956 - accuracy: 0.9723 - val_loss: 0.3072 - val_accuracy: 0.8851
Epoch 8/20
30

In [ ]:
# Evaluation
results = model.evaluate(x_test, y_test)

782/782 [==============================] - 3s 4ms/step - loss: 0.7835 - accuracy: 0.8470


In [ ]:
from prettytable import PrettyTable
# Prediction
preds = model.predict(x_test[0:10])

t = PrettyTable(['Real', 'Predicted'])
for i, pred in enumerate(preds):
    t.add_row([y_test[i], round(preds[i, 0], 2)])
print(t)

1/1 [==============================] - 0s 464ms/step
+------+-----------+
| Real | Predicted |
+------+-----------+
| 0.0  |    0.0    |
| 1.0  |    1.0    |
| 1.0  |    0.93   |
| 0.0  |    0.87   |
| 1.0  |    0.98   |
| 1.0  |    1.0    |
| 1.0  |    0.59   |
| 0.0  |    0.0    |
| 0.0  |    0.85   |
| 1.0  |    1.0    |
+------+-----------+


Now using Simple Recurrent Neural Networks


In [ ]:
from keras.datasets import imdb
from keras.utils import pad_sequences

max_features = 10000
maxlen = 500
batch_size = 32

# Load data and pad it
(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words=max_features)
input_train = pad_sequences(input_train, maxlen=maxlen)
input_test = pad_sequences(input_test, maxlen=maxlen)


Please amend the import in [11]
Code given in tutorial 10 has been updated and from keras import preprocessing import sequence has no longer pad_sequences()
Use instead: from keras.utils import pad_sequences

In [ ]:
from keras.layers import Embedding, SimpleRNN, Dense

# Define model
model = models.Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])

# Train the model
model.fit(input_train, y_train,
          epochs=15,
          batch_size=128,
          validation_split=0.2)


Epoch 1/15
157/157 [==============================] - 26s 155ms/step - loss: 0.6712 - acc: 0.5793 - val_loss: 0.5747 - val_acc: 0.7598
Epoch 2/15
157/157 [==============================] - 30s 193ms/step - loss: 0.4440 - acc: 0.8097 - val_loss: 0.4037 - val_acc: 0.8264
Epoch 3/15
157/157 [==============================] - 27s 169ms/step - loss: 0.3040 - acc: 0.8807 - val_loss: 0.3704 - val_acc: 0.8410
Epoch 4/15
157/157 [==============================] - 26s 169ms/step - loss: 0.2068 - acc: 0.9214 - val_loss: 0.4049 - val_acc: 0.8274
Epoch 5/15
157/157 [==============================] - 25s 159ms/step - loss: 0.1358 - acc: 0.9532 - val_loss: 0.4604 - val_acc: 0.8118
Epoch 6/15
157/157 [==============================] - 24s 153ms/step - loss: 0.0857 - acc: 0.9729 - val_loss: 0.6176 - val_acc: 0.7556
Epoch 7/15
157/157 [==============================] - 25s 162ms/step - loss: 0.0525 - acc: 0.9838 - val_loss: 0.6830 - val_acc: 0.7434
Epoch 8/15
157/157 [==============================] - 2

In [ ]:
# Evaluation
results = model.evaluate(input_test, y_test)

782/782 [==============================] - 21s 27ms/step - loss: 0.8551 - acc: 0.8044


In [ ]:
# Define model
model = models.Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])

# Train the model
model.fit(input_train, y_train,
          epochs=15,
          batch_size=128,
          validation_split=0.2)

Epoch 1/15
157/157 [==============================] - 101s 619ms/step - loss: 0.6889 - acc: 0.5315 - val_loss: 0.5727 - val_acc: 0.7338
Epoch 2/15
157/157 [==============================] - 95s 605ms/step - loss: 0.4316 - acc: 0.8062 - val_loss: 0.4523 - val_acc: 0.7870
Epoch 3/15
157/157 [==============================] - 95s 608ms/step - loss: 0.2674 - acc: 0.8938 - val_loss: 0.5519 - val_acc: 0.7494
Epoch 4/15
157/157 [==============================] - 95s 603ms/step - loss: 0.1636 - acc: 0.9398 - val_loss: 0.5216 - val_acc: 0.8138
Epoch 5/15
157/157 [==============================] - 93s 590ms/step - loss: 0.0784 - acc: 0.9745 - val_loss: 0.6804 - val_acc: 0.8124
Epoch 6/15
157/157 [==============================] - 94s 597ms/step - loss: 0.0435 - acc: 0.9859 - val_loss: 0.9588 - val_acc: 0.7456
Epoch 7/15
157/157 [==============================] - 93s 592ms/step - loss: 0.0233 - acc: 0.9931 - val_loss: 1.1533 - val_acc: 0.7212
Epoch 8/15
157/157 [==============================] - 

In [ ]:
# Evaluation
results = model.evaluate(input_test, y_test)


782/782 [==============================] - 74s 95ms/step - loss: 2.0052 - acc: 0.6876


Same for [11]
Tutorial code has to be updated to make it run correctly
Change the import from keras.layers.recurrent in:
from keras.layers import LSTM

In [ ]:
from keras.layers import LSTM

# Define LSTM network
model = models.Sequential()
model.add(Embedding(max_features, 32))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])

# Train the model
model.fit(input_train, y_train,
          epochs=20,
          batch_size=128,
          validation_split=0.2)


Epoch 1/20
157/157 [==============================] - 65s 401ms/step - loss: 0.4931 - acc: 0.7634 - val_loss: 0.3531 - val_acc: 0.8604
Epoch 2/20
157/157 [==============================] - 54s 344ms/step - loss: 0.2885 - acc: 0.8874 - val_loss: 0.3135 - val_acc: 0.8726
Epoch 3/20
157/157 [==============================] - 55s 353ms/step - loss: 0.2285 - acc: 0.9151 - val_loss: 0.2863 - val_acc: 0.8894
Epoch 4/20
157/157 [==============================] - 54s 346ms/step - loss: 0.1977 - acc: 0.9268 - val_loss: 0.3077 - val_acc: 0.8792
Epoch 5/20
157/157 [==============================] - 54s 343ms/step - loss: 0.1722 - acc: 0.9378 - val_loss: 0.3211 - val_acc: 0.8820
Epoch 6/20
157/157 [==============================] - 54s 343ms/step - loss: 0.1533 - acc: 0.9458 - val_loss: 0.3251 - val_acc: 0.8832
Epoch 7/20
157/157 [==============================] - 55s 350ms/step - loss: 0.1379 - acc: 0.9527 - val_loss: 0.5405 - val_acc: 0.8336
Epoch 8/20
157/157 [==============================] - 5

In [ ]:
# Evaluation
results = model.evaluate(input_test, y_test)

782/782 [==============================] - 36s 46ms/step - loss: 0.7299 - acc: 0.8328
